# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20181005_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='editor',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='article',
            name='post',
        ),
    ]
