# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20181007_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Welcome Me!'),
        ),
    ]
